package com.myteam.relatoriofrete;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pedido implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String filial_operac;

   private int nr_pedido;

   public pedido()
   {
   }

   public int getNr_pedido()
   {
      return this.nr_pedido;
   }

   public void setNr_pedido(int nr_pedido)
   {
      this.nr_pedido = nr_pedido;
   }

   public java.lang.String getFilial_operac()
   {
      return this.filial_operac;
   }

   public void setFilial_operac(java.lang.String filial_operac)
   {
      this.filial_operac = filial_operac;
   }

   public pedido(java.lang.String filial_operac, int nr_pedido)
   {
      this.filial_operac = filial_operac;
      this.nr_pedido = nr_pedido;
   }

}