package com.myteam.relatoriofrete;
import com.myteam.relatoriofrete.roteiro;
import com.myteam.relatoriofrete.containers;
import com.myteam.relatoriofrete.pedido;
import com.myteam.relatoriofrete.item;
import com.myteam.relatoriofrete.cliente;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class principal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private roteiro principal_roteiro;
   private containers principal_containers;
   private pedido principal_pedido;
   private java.math.BigDecimal principal_total;

   private java.util.List<item> principal_item;

   private java.util.List<cliente> principal_cliente;

   public principal()
   {
   }

   public roteiro getPrincipal_roteiro()
   {
      return this.principal_roteiro;
   }

   public void setPrincipal_roteiro(
         roteiro principal_roteiro)
   {
      this.principal_roteiro = principal_roteiro;
   }

   public containers getPrincipal_containers()
   {
      return this.principal_containers;
   }

   public void setPrincipal_containers(
         containers principal_containers)
   {
      this.principal_containers = principal_containers;
   }

   public pedido getPrincipal_pedido()
   {
      return this.principal_pedido;
   }

   public void setPrincipal_pedido(
         pedido principal_pedido)
   {
      this.principal_pedido = principal_pedido;
   }

   public java.math.BigDecimal getPrincipal_total()
   {
      return this.principal_total;
   }

   public void setPrincipal_total(java.math.BigDecimal principal_total)
   {
      this.principal_total = principal_total;
   }

   public java.util.List<item> getPrincipal_item()
   {
      return this.principal_item;
   }

   public void setPrincipal_item(
         java.util.List<item> principal_item)
   {
      this.principal_item = principal_item;
   }

   public java.util.List<cliente> getPrincipal_cliente()
   {
      return this.principal_cliente;
   }

   public void setPrincipal_cliente(
         java.util.List<cliente> principal_cliente)
   {
      this.principal_cliente = principal_cliente;
   }

   public principal(
         roteiro principal_roteiro,
         containers principal_containers,
         pedido principal_pedido,
         java.math.BigDecimal principal_total,
         java.util.List<item> principal_item,
         java.util.List<cliente> principal_cliente)
   {
      this.principal_roteiro = principal_roteiro;
      this.principal_containers = principal_containers;
      this.principal_pedido = principal_pedido;
      this.principal_total = principal_total;
      this.principal_item = principal_item;
      this.principal_cliente = principal_cliente;
   }

}